# Generated by Django 4.1.6 on 2024-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_notification_stud_id_notification_prn'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prn', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_date',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prn', models.CharField(max_length=25)),
            ],
        ),
    ]
