# Generated by Django 4.1.6 on 2024-03-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_studentallocation_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('seats', models.IntegerField()),
                ('columns', models.IntegerField()),
                ('rows', models.IntegerField()),
            ],
            options={
                'db_table': 'room_data',
            },
        ),
    ]
