# Generated by Django 4.1.6 on 2024-03-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_teacherallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentallocation',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='studentallocation',
            name='student_col',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentallocation',
            name='student_row',
            field=models.IntegerField(default=2),
        ),
    ]
